// product-grid/src/index.tsx
import { useEffect, useState } from "react";

interface Product {
  id: number;
  title: string;
  price: number;
  description: string;
  category: string;
  image: string;
  rating: {
    rate: number;
    count: number;
  };
}

const ProductCard = ({ product }: { product: Product }) => {
  return (
    <div className="p-4 border rounded-lg shadow-md bg-white">
      <img
        src={product.image}
        alt={product.title}
        className="w-full h-48 object-cover rounded-lg mb-4"
      />
      <h2 className="text-lg font-semibold mb-2 line-clamp-1 text-primary-500">
        {product.title}
      </h2>
      <p className="text-sm text-gray-600 mb-2 line-clamp-2">
        {product.description}
      </p>
      <p className="text-lg font-bold  text-primary-800">
        ${product.price.toFixed(2)}
      </p>
    </div>
  );
};

const Index = () => {
  const [products, setProducts] = useState<Product[]>([]);

  useEffect(() => {
    fetch("https://fakestoreapi.com/products")
      .then((res) => res.json())
      .then((data) => setProducts(data));
  }, []);

  return (
    <div className="p-4">
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
        {products.map((product) => (
          <ProductCard key={product.id} product={product} />
        ))}
      </div>
    </div>
  );
};

export default Index;

// trusted-business/src/index.svelte
<script lang="ts">
  import { onMount } from "svelte";

  interface Product {
    id: number;
    title: string;
    image: string;
  }

  let products: Product[] = [];
  let isPaused = false;

  onMount(async () => {
    try {
      const response = await fetch("https://fakestoreapi.com/products");
      const data: Product[] = await response.json();
      products = data.map((product) => ({
        id: product.id,
        title: product.title,
        image: product.image,
      }));
    } catch (error) {
      console.error("Failed to fetch products:", error);
    }
  });

  function togglePause() {
    isPaused = !isPaused;
  }
</script>

<div class="scrolling-list-wrapper">
  <div
    class="gap-4 scrolling-list {isPaused ? 'paused' : ''}"
    on:mouseenter={togglePause}
    on:mouseleave={togglePause}
  >
    {#each [...products, ...products, ...products] as product}
      <div
        class="flex-shrink-0 w-48 bg-gray-100 p-4 rounded-lg shadow-md text-center"
      >
        <img
          src={product.image}
          alt={product.title}
          class="w-32 h-32 object-cover mx-auto rounded-md"
        />
        <h2 class="mt-2 text-primary-700 text-sm font-semibold truncate">
          {product.title}
        </h2>
      </div>
    {/each}
  </div>
</div>

<style>
  .scrolling-list-wrapper {
    overflow: hidden;
    position: relative;
    width: 100%;
  }
  .scrolling-list {
    display: flex;
    animation: scroll 30s linear infinite;
    white-space: nowrap;
    padding: 1rem;
  }
  .scrolling-list.paused {
    animation-play-state: paused;
  }

  @keyframes scroll {
    0% {
      transform: translateX(0);
    }
    100% {
      transform: translateX(-100%);
    }
  }
</style>
